export const ACTION_TYPES = {
    SET_VERSION: 'SET_VERSION',
    SET_VIDEO_LIST: 'SET_VIDEO_LIST',
    SET_STICKY_HEADER: 'SET_STICKY_HEADER',
    SET_COLOR: 'SET_COLOR',
    SET_POSITION: 'SET_POSITION',
    SET_SCROLLING: 'SET_SCROLLING',
    SET_BOARD_LIST: 'SET_BOARD_LIST',
    SET_IMAGE_LIST_BY_BOARD_ID: 'SET_IMAGE_LIST_BY_BOARD_ID',
};