export const ACTION_TYPES = {
    SET_VERSION: 'SET_VERSION',
    SET_VIDEO_LIST: 'SET_VIDEO_LIST',
    SET_STICKY_HEADER: 'SET_STICKY_HEADER',
    SET_COLOR: 'SET_COLOR',
    SET_POSITION: 'SET_POSITION',
};